version: '3'
services:
  food-db:
    container_name: food-db
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - '127.0.0.1:5454:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=custom
      - POSTGRES_PASSWORD=qwerty123
    volumes:
      - ./db_data:/var/lib/postgresql/data
