version: '3'
services:
  minio:
    image: minio/minio
    container_name: food-minio
    ports:
      - 9004:9000
      - 9003:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: changeme