base_api_url = "http://localhost:8091"
base_host = "localhost:8091"
base_admin_api_url = "http://localhost:8092"
bind_addr = "0.0.0.0:8091"
admin_addr = "0.0.0.0:8092"
log_level = "debug"
database_url = "host=localhost user=custom password=qwerty123 dbname=django port=5454 sslmode=disable"
access_token_ttl = 24
refresh_token_ttl = 720
token_secret = "asdfasdfasdfasdfasfd"
admin_access_token_ttl = 24
admin_token_secret = "qweqweqweqweqweqweqweqweqweqweqeqwe"

minio_endpoint = "localhost:9004"
minio_access_key = "root"
minio_secret_key = "changeme"
minio_use_ssl = false
