basePath: /
host: localhost:8082
info:
  contact: {}
  description: Admin API Server for FOOD Application
  title: Food Admin API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
