# Generated by Django 4.2.8 on 2024-01-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_diet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietitem",
            name="diet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app_diet.diet",
            ),
        ),
    ]
