# Generated by Django 4.2.8 on 2024-01-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_diet", "0002_alter_dietitem_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietitem",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diet_items_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
