basePath: /
definitions:
  model.CreateProduct:
    properties:
      calories:
        type: integer
      carbohydrates:
        type: number
      description:
        type: string
      fats:
        type: number
      slug:
        type: string
      squirrels:
        type: number
      title:
        type: string
    required:
    - calories
    - carbohydrates
    - fats
    - slug
    - squirrels
    - title
    type: object
  model.Login:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  model.LoginConfirm:
    properties:
      code:
        type: string
      id:
        type: integer
    required:
    - code
    - id
    type: object
  model.LoginConfirmResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
  model.LoginResponse:
    properties:
      id:
        type: integer
    type: object
  model.Product:
    properties:
      calories:
        type: integer
      carbohydrates:
        type: number
      description:
        type: string
      fats:
        type: number
      id:
        type: integer
      photo:
        type: string
      slug:
        type: string
      squirrels:
        type: number
      title:
        type: string
    type: object
  model.ProductList:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Product'
        type: array
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  model.UpdateProduct:
    properties:
      calories:
        type: integer
      carbohydrates:
        type: number
      description:
        type: string
      fats:
        type: number
      slug:
        type: string
      squirrels:
        type: number
      title:
        type: string
    type: object
  model.UpdateUser:
    properties:
      birthday:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
  model.User:
    properties:
      birthday:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone:
        type: string
      photo:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      detail:
        type: string
    type: object
host: localhost:8091
info:
  contact: {}
  description: API Server for FOOD Application
  title: Food API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: SignUp
      tags:
      - Auth
  /login/confirm:
    post:
      consumes:
      - application/json
      description: Generate access/refresh tokens
      operationId: generate-tokens
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.LoginConfirm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginConfirmResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Confirm Code
      tags:
      - Auth
  /login/refresh:
    post:
      description: Generate new access/refresh tokens
      operationId: refresh-tokens
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginConfirmResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh token
      tags:
      - Auth
  /v1/product:
    get:
      consumes:
      - application/json
      description: Get product list
      operationId: get-product-list
      parameters:
      - default: 25
        description: limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: offset
        in: query
        name: offset
        type: integer
      - in: query
        name: calories__gte
        type: integer
      - in: query
        name: calories__lte
        type: integer
      - in: query
        name: carbohydrates__gte
        type: number
      - in: query
        name: carbohydrates__lte
        type: number
      - in: query
        name: fats__gte
        type: number
      - in: query
        name: fats__lte
        type: number
      - in: query
        name: slug
        type: string
      - in: query
        name: squirrels__gte
        type: number
      - in: query
        name: squirrels__lte
        type: number
      - in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProductList'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get product list
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: Create product
      operationId: create-product
      parameters:
      - description: product info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.CreateProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create product
      tags:
      - Product
  /v1/product/{id}:
    delete:
      consumes:
      - application/json
      description: Delete product
      operationId: delete-product
      parameters:
      - description: Product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete product
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: Get product by id
      operationId: get-product
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get product by id
      tags:
      - Product
    patch:
      consumes:
      - application/json
      description: Update product
      operationId: update-product
      parameters:
      - description: Product update data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.UpdateProduct'
      - description: Product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update product
      tags:
      - Product
  /v1/product/{id}/photo:
    delete:
      description: Delete product photo
      operationId: delete-product-photo
      parameters:
      - description: Product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      security:
      - ApiKeyAuth: []
      summary: Delete photo
      tags:
      - Product
    post:
      consumes:
      - multipart/form-data
      description: Upload product photo
      operationId: upload-product-photo
      parameters:
      - description: Product id
        in: path
        name: id
        required: true
        type: integer
      - description: this is a test file
        in: formData
        name: photo
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload photo
      tags:
      - Product
  /v1/profile:
    get:
      description: Get current user
      operationId: get-current-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get current user
      tags:
      - Profile
    patch:
      consumes:
      - application/json
      description: Update current user
      operationId: update-current-user
      parameters:
      - description: User udpate data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update current profile
      tags:
      - Profile
  /v1/profile/photo:
    delete:
      description: Delete profile photo
      operationId: delete-profile-photo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete photo
      tags:
      - Profile
    post:
      consumes:
      - multipart/form-data
      description: Upload profile photo
      operationId: upload-profile-photo
      parameters:
      - description: this is a test file
        in: formData
        name: photo
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload photo
      tags:
      - Profile
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
